name: retryable
description: make operation retryable.
version: 0.0.3
homepage: https://github.com/neutronstarer/flutter_retryable

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  cancelable: ^0.0.3

dev_dependencies:
  test: